window.MEMO_PRODUCTS = [
{id:"M01",name:"Square Bra Tank",category:"Inner → Outer",price:359,colors:["Rose","Lilac","Cream"],sizes:["XS","S","M","L","XL","XXL"],mood:"Clean support, designed to be seen.",accent:"#f8b9ce"},
{id:"M02",name:"Asymmetric Cami",category:"Inner → Outer",price:389,colors:["Lilac","Sky Blue","Cream"],sizes:["XS","S","M","L","XL"],mood:"One shoulder, one small bow, zero fuss.",accent:"#cbb9ee"},
{id:"M03",name:"Rib Bra Top",category:"Inner → Outer",price:329,colors:["Mint","Cream","Rose"],sizes:["XS","S","M","L","XL","XXL"],mood:"Pointelle rib with contrast trim.",accent:"#bfe0cd"},
{id:"M04",name:"Soft Balconette",category:"Inner → Outer",price:399,colors:["Champagne","Rose","Sky Blue"],sizes:["XS","S","M","L","XL"],mood:"Light structure with cat charm fastening.",accent:"#f1d6b9"},
{id:"M05",name:"Back Detail Cami",category:"Inner → Outer",price:369,colors:["Cream","Rose","Mint"],sizes:["XS","S","M","L","XL"],mood:"Quiet front, playful back.",accent:"#fff1e7"},
{id:"M06",name:"Longline Bralette",category:"Inner → Outer",price:359,colors:["Rose","Pool Blue","Lilac"],sizes:["XS","S","M","L","XL"],mood:"Longline proportion for real outerwear.",accent:"#f0b3cb"},
{id:"M07",name:"Mid Brief",category:"Intimates",price:149,colors:["Rose","Cream","Lilac","Mint"],sizes:["XS","S","M","L","XL","XXL"],mood:"Everyday soft coverage.",accent:"#f8c5d6"},
{id:"M08",name:"High Brief",category:"Intimates",price:169,colors:["Cream","Rose","Sage"],sizes:["XS","S","M","L","XL","XXL"],mood:"More coverage, same mood.",accent:"#e8e3d7"},
{id:"M09",name:"Boy Short",category:"Intimates",price:189,colors:["Sky Blue","Rose","Cream"],sizes:["XS","S","M","L","XL","XXL"],mood:"Travel, sleep, move.",accent:"#bdd5f0"},
{id:"M10",name:"Soft Cheeky",category:"Intimates",price:169,colors:["Rose","Lilac","Butter"],sizes:["XS","S","M","L","XL"],mood:"Play version with better fit.",accent:"#f4afc4"},
{id:"M11",name:"Washable Silk Cami",category:"Silk & Lounge",price:459,colors:["Rose","Champagne","Lilac"],sizes:["XS","S","M","L","XL"],mood:"Bias cut with a clean luminous surface.",accent:"#f0bfd0"},
{id:"M12",name:"Silk Short",category:"Silk & Lounge",price:459,colors:["Rose","Sky Blue","Champagne"],sizes:["XS","S","M","L","XL"],mood:"Real pockets, soft waist, polished hem.",accent:"#ebc3cd"},
{id:"M13",name:"Silk Shirt",category:"Silk & Lounge",price:659,colors:["Sky Blue","Cream","Rose"],sizes:["XS","S","M","L","XL"],mood:"Hidden snap + contrast piping.",accent:"#bfd5ee"},
{id:"M14",name:"Silk Pant",category:"Silk & Lounge",price:659,colors:["Lilac","Pearl","Rose"],sizes:["XS","S","M","L","XL"],mood:"Front-clean waist, petite/regular length.",accent:"#d1c1ef"},
{id:"M15",name:"Robe Jacket",category:"Silk & Lounge",price:759,colors:["Peach","Cream","Lilac"],sizes:["XS","S","M","L","XL"],mood:"Bed, breakfast, city.",accent:"#f1c9bd"},
{id:"M16",name:"Silk Slip Midi",category:"Business → Bar",price:699,colors:["Rose","Champagne","Lilac"],sizes:["XS","S","M","L","XL"],mood:"Asymmetric drape for day-to-night.",accent:"#efb5c9"},
{id:"M17",name:"Modal Short Set",category:"Silk & Lounge",price:499,colors:["Mint","Rose","Sky Blue"],sizes:["XS","S","M","L","XL","XXL"],mood:"Soft air for warm cities.",accent:"#bfe0cd"},
{id:"M18",name:"Modal Long Set",category:"Silk & Lounge",price:599,colors:["Lilac","Cream","Sky Blue"],sizes:["XS","S","M","L","XL","XXL"],mood:"Plane, hotel, sleep.",accent:"#d2c6ee"},
{id:"M19",name:"City Easy Pant",category:"Travel",price:429,colors:["Cream","Sky Blue","Sage"],sizes:["XS","S","M","L","XL"],mood:"Not a pajama pant.",accent:"#e8e1d2"},
{id:"M20",name:"Travel Cardigan",category:"Travel",price:429,colors:["Rose","Lilac","Cream"],sizes:["XS","S","M","L","XL"],mood:"Cold cabin, good mood.",accent:"#efc6d3"},
{id:"M21",name:"Square Bikini Top",category:"Swim & Resort",price:359,colors:["Pool Blue","Rose","Butter","Mint"],sizes:["XS","S","M","L","XL"],mood:"Stable, clean, sun-ready.",accent:"#9ed1ee"},
{id:"M22",name:"Triangle Bikini Top",category:"Swim & Resort",price:329,colors:["Rose","Lilac","Butter"],sizes:["XS","S","M","L","XL"],mood:"Adjustable with regular/full fit logic.",accent:"#f4b4c8"},
{id:"M23",name:"Classic Swim Bottom",category:"Swim & Resort",price:269,colors:["Pool Blue","Rose","Mint"],sizes:["XS","S","M","L","XL","XXL"],mood:"Easy coverage.",accent:"#9fd5ee"},
{id:"M24",name:"High-Waist Swim Bottom",category:"Swim & Resort",price:299,colors:["Butter","Mint","Rose"],sizes:["XS","S","M","L","XL","XXL"],mood:"Cover version, still playful.",accent:"#f2dd8d"},
{id:"M25",name:"Swim Bodysuit",category:"Swim & Resort",price:599,colors:["Mint","Pool Blue","Rose"],sizes:["XS","S","M","L","XL"],mood:"Swim now, denim later.",accent:"#b9ddc8"},
{id:"M26",name:"Swim Short",category:"Swim & Resort",price:329,colors:["Pool Blue","Cream","Rose"],sizes:["XS","S","M","L","XL"],mood:"Walk, paddle, play.",accent:"#b9d4ef"},
{id:"M27",name:"Resort Shirt",category:"Travel",price:499,colors:["Floral","Sky Blue","Cream"],sizes:["XS","S","M","L","XL"],mood:"Wet swim, lunch, city.",accent:"#eacbd5"},
{id:"M28",name:"Wrap Skirt",category:"Travel",price:399,colors:["Rose","Lilac","Floral"],sizes:["XS","S","M","L","XL"],mood:"Pool edge to dinner.",accent:"#f0b9c9"},
{id:"M29",name:"Easy Shirt Dress",category:"Business → Bar",price:599,colors:["Cream","Rose","Sky Blue"],sizes:["XS","S","M","L","XL"],mood:"Sleep layer, cover-up, city dress.",accent:"#efe1d9"},
{id:"M30",name:"Foldable Travel Set",category:"Travel",price:799,colors:["Cream","Lilac","Sky Blue"],sizes:["XS","S","M","L","XL"],mood:"One pouch, a full travel mood.",accent:"#ded3ef"},
{id:"O01",name:"MEMO Work Tote",category:"Objects",price:699,colors:["Cream","Rose","Sky Blue"],sizes:["One Size"],mood:"Laptop, document, bottle, good mood.",accent:"#f0dfd6"},
{id:"O02",name:"MEMO Crossbody",category:"Objects",price:459,colors:["Rose","Cream","Lilac"],sizes:["One Size"],mood:"Hands free, city ready.",accent:"#efc1d0"},
{id:"O03",name:"MEMO Evening Clutch",category:"Objects",price:399,colors:["Rose","Lilac","Champagne"],sizes:["One Size"],mood:"Small bag, big mood.",accent:"#e6c8df"},
{id:"O04",name:"MEMO Tumbler Bucket",category:"Objects",price:529,colors:["Rose","Mint","Cream"],sizes:["One Size"],mood:"A vertical drink compartment, finally.",accent:"#eec7d1"},
{id:"O05",name:"Variable Cat Charm",category:"Objects",price:129,colors:["Gold","Rose Gold","Silver"],sizes:["One Size"],mood:"Collect your cats.",accent:"#f2d497"}
];