from pathlib import Path
import json,html
ROOT=Path(__file__).resolve().parents[1];D=ROOT/'docs';D.mkdir(exist_ok=True)
V='locked-20260920-r1'
P=[
 dict(id='scallop-bow-bra',name='Scallop Bow Bra Set',price=49,image='product-bra',photo='cat-lingerie',categories=['lingerie','travel'],colors=['Blossom Pink','Cloud Blue','Cream'],shown='Blossom Pink',sizes=['XS','S','M','L','XL'],description='A little scallop. A little bow. A brighter start to the day.',details=['Floral print and scalloped edges','Bow at the centre front','Coordinated top and brief concept'],pair=['dreamy-kimono','kitty-charm-pj']),
 dict(id='kitty-charm-pj',name='Kitty Charm PJ Set',price=79,image='product-pajamas',photo='cat-lounge',categories=['lounge','travel'],colors=['Blossom Pink','Cloud Blue','Cream'],shown='Blossom Pink',sizes=['XS','S','M','L','XL'],description='Cat-print mornings, unhurried afternoons. The soft side of a travel wardrobe.',details=['Signature line-cat print','Contrast piping and a notched collar','Shirt and shorts designed as a matching set'],pair=['scallop-bow-bra','ribbon-onepiece']),
 dict(id='ribbon-onepiece',name='Ribbon One-piece',price=89,image='product-onepiece',photo='cat-swim',categories=['swim','travel'],colors=['Pool Blue','Blossom Pink','Cream'],shown='Pool Blue',sizes=['XS','S','M','L','XL'],description='Pool blue, side ribbons, sunshine. One piece with its own personality.',details=['V-shaped neckline','Side tie and cut-out design','Bow details in a contrasting light tone'],pair=['dreamy-kimono','rose-garden-slip']),
 dict(id='ruffle-bikini',name='Ruffle Bikini Set',price=64,image='product-bikini',photo='cat-swim',categories=['swim','travel'],colors=['Blossom Pink','Pool Blue','Cream'],shown='Blossom Pink',sizes=['XS','S','M','L','XL'],description='A playful pink mood, finished with small frills rather than more fuss.',details=['Ruffled shoulder straps and edges','Coordinated floral top and bottom','Small bow detailing'],pair=['dreamy-kimono','kitty-charm-pj']),
 dict(id='rose-garden-slip',name='Rose Garden Slip Dress',price=88,image='product-dress',photo='cat-business',categories=['lounge','business','travel'],colors=['Peach Floral','Cloud Blue','Cream'],shown='Peach Floral',sizes=['XS','S','M','L','XL'],description='From a slow breakfast to the last table outside. A fresh floral layer for every version of your day.',details=['Fine shoulder straps','Floral print and softly flared shape','Pair with an outer layer for the city'],pair=['dreamy-kimono','memo-cat-pouch']),
 dict(id='dreamy-kimono',name='Dreamy Kimono Robe',price=92,image='product-robe',photo='cat-lounge',categories=['lounge','business','travel'],colors=['Blossom Pink','Cloud Blue','Cream'],shown='Blossom Pink',sizes=['XS','S','M','L','XL'],description='Same cat, different room. A robe-shaped layer for your good-mood ritual.',details=['Wrap front with a self-tie belt','MEMO cat-print design','Contrast trim along the front and cuffs'],pair=['scallop-bow-bra','ribbon-onepiece']),
 dict(id='memo-cat-pouch',name='MEMO Cat Pouch',price=None,image='cat-objects',photo='cat-objects',categories=['objects','travel'],colors=['Blossom Pink'],shown='Blossom Pink',sizes=['One size'],description='Little things. Brighter days. The familiar line cat goes wherever you do.',details=['Pink zip-pouch concept','Signature black line-cat artwork','Gold-tone detail in the visual concept'],pair=['rose-garden-slip','kitty-charm-pj'])
]
CAT=[('lingerie','Lingerie','Soft. Bold. Playful. Yours.','cat-lingerie'),('lounge','Silk & Lounge','Comfort looks good on you.','cat-lounge'),('business','Business → Bar','One look. More possibilities.','cat-business'),('travel','Travel Capsule','Outfits for everywhere.','cat-travel'),('swim','Swim & Resort','Sun. Salt. Self Love.','cat-swim'),('objects','Objects & Accessories','Little things. Brighter days.','cat-objects')]
S={'search':'<circle cx="10.5" cy="10.5" r="6.8"/><path d="m16 16 5 5"/>','heart':'<path d="M20.8 4.6a5.4 5.4 0 0 0-7.7 0L12 5.7l-1.1-1.1a5.4 5.4 0 0 0-7.7 7.7L12 21l8.8-8.7a5.4 5.4 0 0 0 0-7.7Z"/>','bag':'<path d="M5 7h14l1.2 14H3.8L5 7Z"/><path d="M8 8V6a4 4 0 0 1 8 0v2"/>','arrow':'<path d="M4 12h15M13 6l6 6-6 6"/>','close':'<path d="m6 6 12 12M18 6 6 18"/>','menu':'<path d="M4 6h16M4 12h16M4 18h16"/>','sun':'<circle cx="12" cy="12" r="4"/><path d="M12 1v3m0 16v3M1 12h3m16 0h3M4.2 4.2l2 2m11.6 11.6 2 2M4.2 19.8l2-2M17.8 6.2l2-2"/>','plane':'<path d="m3 10 7 2 5-9 3-1-3 10 6 3v2l-7-1-3 6-2-1 1-6-7-3Z"/>','bow':'<path d="M12 10C2 0 1 6 3 9s7 3 9 1Zm0 0c10-10 11-4 9-1s-7 3-9 1ZM11 11 6 22m7-11 5 11"/>'}
def icon(n,cls=''):
 return f'<svg class="icon {cls}" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">{S[n]}</svg>'
def image(name,alt,cls='',eager=False):
 return f'<img src="assets/locked/{name}.webp" alt="{html.escape(alt,quote=True)}" class="{cls}" loading="{"eager" if eager else "lazy"}" decoding="async"'+(' fetchpriority="high"' if eager else '')+'>'
def button_arrow():return icon('arrow')
def header():
 return f'''<a class="skip" href="#main">Skip to content</a><div class="topbar"><span>♡ A BRIGHTER YOU, EVERYWHERE</span><span>SAME CAT · DIFFERENT MOOD</span><button data-club>Join MEMO Club ♡</button></div>
<header class="site-header"><a href="index.html" class="brand" aria-label="MEMO home"><span><b>MEMO</b><small>MEMORY OF THE UNIVERSE</small></span>{image('logo-cat','',eager=True)}</a><button class="icon-button mobile-menu" data-menu aria-label="Open navigation" aria-expanded="false" aria-controls="navigation">{icon('menu')}</button><nav id="navigation" aria-label="Main navigation"><a href="shop.html">SHOP</a><a href="shop.html?cat=lingerie">LINGERIE</a><a href="shop.html?cat=lounge">LOUNGEWEAR</a><a href="shop.html?cat=swim">SWIM</a><a href="travel.html">TRAVEL</a><a href="shop.html?cat=objects">ACCESSORIES</a><a href="world.html">OUR WORLD</a></nav><div class="header-tools"><button class="icon-button" data-search aria-label="Search the collection">{icon('search')}</button><a class="icon-button" href="wishlist.html" aria-label="Your wishlist">{icon('heart')}</a><button class="bag-button" data-bag>{icon('bag')}<span>BAG · <b data-bag-count>0</b></span></button></div></header>'''
def footer():
 return f'''<footer class="site-footer"><div class="footer-top"><a class="brand" href="index.html"><span><b>MEMO</b><small>MEMORY OF THE UNIVERSE</small></span></a><nav aria-label="Footer navigation"><a href="world.html">ABOUT</a><a href="travel.html">TRAVEL</a><a href="shop.html">COLLECTION</a><a href="contact.html">CONTACT</a></nav><button class="club-pill" data-club>Join our good mood club {button_arrow()}</button><span class="signature">A brighter you.<br>Everywhere ♡</span></div><div class="footer-bottom"><span>© 2026 MEMO. ALL FOR A BRIGHTER YOU.</span><span><a href="size-guide.html">FIT NOTES</a><a href="policies.html">PREVIEW & PRIVACY</a></span></div><p class="disclosure">Collection preview · AI-created design visuals · Concept prices only. Orders and email subscriptions are not open.</p></footer>'''
def dialogs():
 return f'''<dialog id="bag-dialog" class="bag-dialog"><div class="dialog-heading"><h2>Your Bag <span>♡</span></h2><button class="icon-button" data-close aria-label="Close bag">{icon('close')}</button></div><p class="micro">YOUR GOOD-MOOD EDIT · PREVIEW BAG</p><div data-bag-lines class="bag-lines"></div><div class="bag-bottom"><div class="total"><span>Estimated total</span><strong data-total>$0</strong></div><p>Concept prices in USD. No order has been placed.</p><a class="button secondary full" href="cart.html">VIEW YOUR BAG {button_arrow()}</a><button class="button full" data-sales>LAUNCH & CHECKOUT STATUS {button_arrow()}</button></div></dialog>
<dialog id="search-dialog" class="search-dialog"><div class="dialog-heading"><h2>Find your mood.</h2><button class="icon-button" data-close aria-label="Close search">{icon('close')}</button></div><label for="search-input" class="micro">SEARCH THE COLLECTION</label><input id="search-input" type="search" placeholder="Try pink, swim, robe or travel…" autocomplete="off"><div data-search-results class="search-results" aria-live="polite"></div></dialog>
<dialog id="info-dialog" class="info-dialog"><button class="icon-button info-close" data-close aria-label="Close">{icon('close')}</button><p class="eyebrow">MEMO · GOOD MOOD CLUB</p><h2 data-info-title></h2><p data-info-text></p><button class="button" data-close>BACK TO MEMO {button_arrow()}</button></dialog><div class="toast" id="toast" role="status" aria-live="polite"></div>'''
def card(p):
 price='$'+str(p['price']) if p['price'] is not None else 'Coming soon'
 return f'''<article class="product-card" data-product="{p['id']}"><div class="product-image"><a href="product.html?id={p['id']}" aria-label="View {p['name']}">{image(p['image'],p['name']+' — '+p['shown'])}</a><button class="wish-button" data-wish="{p['id']}" aria-label="Save {p['name']}" aria-pressed="false">{icon('heart')}</button></div><div class="product-meta"><a href="product.html?id={p['id']}" class="product-name">{p['name']}</a><span class="price">{price}</span><div class="swatches" aria-label="Planned palette"><i class="pink"></i><i class="blue"></i><i class="cream"></i></div><a class="view-product" href="product.html?id={p['id']}">EXPLORE {button_arrow()}</a></div></article>'''
def benefits():
 return '<section class="benefits" aria-label="MEMO design philosophy">'+''.join(f'<div>{icon(i)}<span><b>{t}</b><small>{s}</small></span></div>' for i,t,s in [('bow','Thoughtful details','A little joy, beautifully placed'),('sun','All-day ease','The way we want to feel'),('plane','Travel ready','Home is a feeling'),('heart','Young at heart','Designed around real life')])+'</section>'
def page(name,title,content,route='default'):
 canonical='https://memo.saga1001.com/'+('' if name=='index.html' else name)
 out=f'''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#fac9df"><meta name="memo-release" content="{V}"><meta name="description" content="MEMO — Memory of the Universe. The good-mood collection: lingerie, lounge, swim, travel and little cat-inspired things."><title>{html.escape(title)} — MEMO</title><link rel="canonical" href="{canonical}"><meta property="og:title" content="MEMO — Wear Your Good Mood"><meta property="og:description" content="Same girl. Different scenery. Explore the MEMO collection preview."><meta property="og:type" content="website"><meta property="og:url" content="{canonical}"><meta property="og:image" content="https://memo.saga1001.com/assets/locked/hero-desktop.webp"><link rel="icon" href="assets/favicon.svg" type="image/svg+xml"><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;600;700&family=Playfair+Display:ital,wght@0,400;0,500;0,600;1,400;1,500&display=swap" rel="stylesheet"><link rel="stylesheet" href="site.css?v={V}"><script defer src="catalog.js?v={V}"></script><script defer src="site.js?v={V}"></script></head><body data-page="{route}">{header()}<main id="main">{content}</main>{footer()}{dialogs()}</body></html>'''
 (D/name).write_text(out)
category_html='<section class="category-row" aria-label="Shop by mood">'+''.join(f'<a class="category" href="{("travel.html" if k=="travel" else "shop.html?cat="+k)}">{image(im,t)}<div><h2>{t}</h2><p>{s}</p><span class="round-arrow">{button_arrow()}</span></div></a>' for k,t,s,im in CAT)+'</section>'
home=f'''<section class="hero"><h1 class="sr-only">Wear Your Good Mood. A brighter you, everywhere.</h1><picture><source media="(max-width:680px)" srcset="assets/locked/hero-mobile.webp">{image('hero-desktop','The selected MEMO campaign: pink floral lingerie and cat-print robe, a grey-white cat, pastel suitcase and flowers above the Mediterranean sea.',eager=True)}</picture><a class="button hero-cta" href="shop.html">SHOP NEW ARRIVALS {button_arrow()}</a><div class="mobile-hero-copy"><p class="eyebrow">SAME GIRL. DIFFERENT SCENERY.</p><h2>Wear Your<br><em>Good Mood.</em></h2><a class="button" href="shop.html">EXPLORE THE COLLECTION {button_arrow()}</a></div></section>
{category_html}<section class="arrivals" id="arrivals"><header class="section-heading"><div><h2>New Arrivals</h2><p>FRESH MOODS FOR A BRIGHTER YOU.</p></div><div class="filters" role="group" aria-label="Filter new arrivals"><button class="active" data-home-filter="all" aria-pressed="true">ALL</button><button data-home-filter="lingerie" aria-pressed="false">LINGERIE</button><button data-home-filter="lounge" aria-pressed="false">LOUNGEWEAR</button><button data-home-filter="swim" aria-pressed="false">SWIM</button><a href="shop.html">VIEW ALL {button_arrow()}</a></div></header><div class="product-grid" data-home-products>{''.join(card(p) for p in P[:6])}</div></section>
<section class="campaign-grid"><article class="travel-feature">{image('feature-travel','MEMO Travel Capsule: pink luggage, passport, cat pouch, postcards and a straw hat.')}<h2 class="sr-only">MEMO Travel Capsule. From beach to city.</h2><a class="button campaign-cta" href="travel.html">EXPLORE THE COLLECTION {button_arrow()}</a></article><article class="swim-feature">{image('feature-swim','Sun, salt, self love: MEMO blue gingham swim styling by the sea.')}<h2 class="sr-only">Sun. Salt. Self Love.</h2><a class="button campaign-cta" href="shop.html?cat=swim">SHOP SWIM {button_arrow()}</a></article></section>
{benefits()}<a class="world-banner" href="world.html" aria-label="Explore the MEMO world">{image('world-strip','MEMO travel diary: cat, flowers, coastal views, postcards and a brighter you, everywhere.')}</a>'''
page('index.html','Wear Your Good Mood',home,'home')
shop=f'''<section class="collection-intro"><p class="eyebrow">SEASON 01 / THE GOOD MOOD COLLECTION</p><h1 data-collection-title>Find your good mood.</h1><p data-collection-copy>One small collection. Many ways to feel like yourself.</p></section><section class="catalog-wrap"><div class="catalog-toolbar"><div class="filters" data-catalog-filters role="group" aria-label="Collection categories">{''.join(f'<button data-category="{k}" aria-pressed="false">{t}</button>' for k,t in [('all','ALL'),('lingerie','LINGERIE'),('lounge','LOUNGE'),('swim','SWIM'),('business','BUSINESS → BAR'),('travel','TRAVEL'),('objects','ACCESSORIES')])}</div><label class="sort-label">Sort <select id="sort-select"><option value="featured">Featured</option><option value="price-up">Price: low to high</option><option value="price-down">Price: high to low</option></select></label></div><p class="result-count" data-result-count></p><div class="product-grid catalog-grid" data-catalog-products>{''.join(card(p) for p in P)}</div><p class="preview-note">Design preview. Prices are indicative; materials, fit and production availability will be confirmed before orders open.</p></section>'''
page('shop.html','The Collection',shop,'shop')
product='''<div class="breadcrumb"><a href="index.html">Home</a> / <a href="shop.html">Collection</a> / <span data-product-breadcrumb>Design detail</span></div><section class="product-detail" data-product-detail></section><section class="arrivals related"><header class="section-heading"><div><h2>Wear it your way.</h2><p>GOOD COMPANY FOR YOUR NEXT GOOD DAY.</p></div><a href="shop.html">EXPLORE ALL →</a></header><div class="product-grid related-grid" data-related></div></section>'''
page('product.html','Design Detail',product,'product')
travel=f'''<section class="editorial-intro"><div><p class="eyebrow">MEMO TRAVEL CAPSULE</p><h1>One bag.<br><em>More good days.</em></h1><p>From beach to city. Three to five looks, a few familiar layers and small things that make the journey yours.</p><a class="button" href="shop.html?cat=travel">EXPLORE TRAVEL PIECES {button_arrow()}</a></div>{image('feature-travel','The selected MEMO travel capsule artwork',eager=True)}</section><section class="travel-story"><div class="travel-tabs" role="group" aria-label="Travel scene"><button class="active" data-scene="departure">On the way</button><button data-scene="meeting">Meeting → Bar</button><button data-scene="rest">Hotel reset</button><button data-scene="resort">Pool & resort</button></div><div class="scene-content" data-scene-content></div></section><section class="packing"><p class="eyebrow">THE LITTLE PACKING LIST</p><h2>Pack the possibilities.</h2><div class="packing-grid"><article><h3>The layers</h3><p>Two inner layers, a light jacket, one city bottom, a lounge set, a slip dress and swimwear. Repeat the pieces you love.</p></article><article><h3>The shoes</h3><p>A comfortable walking shoe and a low evening shoe. Add training shoes only when your trip includes a workout.</p></article><article><h3>The small things</h3><p>Work tote, compact pouch, scarf, glasses and a light cover-up. Leave space for something you find along the way.</p></article></div></section>'''
page('travel.html','Travel Capsule',travel,'travel')
world=f'''<section class="editorial-intro world-intro"><div><p class="eyebrow">MEMORY OF THE UNIVERSE</p><h1>More love.<br><em>More life.</em></h1><p>MEMO is a little world built around the things we remember: a beautiful morning, a favourite colour, a familiar cat, a trip that feels like you.</p><p>Inside and outside. Rest and adventure. We are designing a wardrobe for the transitions — with clean shapes, playful colour and a few details worth keeping.</p><a class="button" href="shop.html">MEET THE COLLECTION {button_arrow()}</a></div>{image('cat-lingerie','The selected MEMO pink floral look with the grey-white cat',eager=True)}</section><section class="world-values"><article><h2>Same cat.</h2><p>A simple line cat, a quiet observer. On a robe, a pouch or a tiny detail — it belongs to the same MEMO world.</p></article><article><h2>Different mood.</h2><p>Peach pink, lilac, pool blue, butter and cream. Colour is a way to play, not a uniform.</p></article><article><h2>Still you.</h2><p>Clean first. Then a scallop, a ribbon or a small contrast. Personality without putting every idea on one piece.</p></article></section><div class="world-banner">{image('world-strip','The MEMO diary of cats, flowers and coastal memories')}</div>'''
page('world.html','Our World',world,'world')
page('wishlist.html','Your Wishlist','''<section class="collection-intro"><p class="eyebrow">SAVED FOR A BRIGHTER DAY</p><h1>Your little favourites.</h1><p>Your wishlist stays in this browser. No account or email address is needed.</p></section><section class="catalog-wrap"><div class="product-grid catalog-grid" data-wishlist-products></div></section>''','wishlist')
page('cart.html','Your Bag','''<section class="collection-intro"><p class="eyebrow">YOUR PERSONAL GOOD-MOOD EDIT</p><h1>Your Bag.</h1><p>Preview your chosen colours and sizes. This is not an order.</p></section><section class="cart-page"><div data-cart-page-lines></div><aside><h2>The little summary</h2><div class="total"><span>Estimated total</span><strong data-total>$0</strong></div><p>Indicative USD prices. Taxes, shipping, stock and final fit are not confirmed.</p><button class="button full" data-sales>LAUNCH & CHECKOUT STATUS →</button><a class="text-link" href="shop.html">Continue exploring</a></aside></section>''','cart')
page('size-guide.html','Fit Notes','''<section class="text-page"><p class="eyebrow">MEMO FIT NOTES</p><h1>A fit that feels like you.</h1><p>The collection is currently a design preview. Size labels in the preview bag are planning options, not confirmed garment measurements.</p><h2>Before orders open</h2><p>Each style needs its own finished measurements, fit testing and size chart. We will publish these with the final composition and care instructions. A single generic size conversion is not a substitute for that work.</p><h2>Know your own measurements</h2><p>Keep a note of your bust, underbust, waist and fullest hip measurement, without pulling the tape tight. Compare them with the specific style chart once it is available.</p><a class="button" href="shop.html">BACK TO THE COLLECTION →</a></section>''')
page('contact.html','Contact & Launch','''<section class="text-page"><p class="eyebrow">HELLO, GOOD MOOD</p><h1>The next chapter is getting dressed.</h1><p>MEMO is currently a collection and brand preview. The website does not yet accept paid orders, email signups or customer-service requests.</p><h2>MEMO Club</h2><p>There is no active mailing-list connection on this site. Clicking the club button does not submit or store your email address.</p><h2>Launch information</h2><p>Verified business contact details, availability, delivery destinations and customer-care information will be published before sales open.</p><a class="button" href="shop.html">EXPLORE MEMO →</a></section>''')
page('policies.html','Preview & Privacy','''<section class="text-page"><p class="eyebrow">A CLEAR PREVIEW</p><h1>What this site does.</h1><h2>Collection status</h2><p>Images show AI-created fashion design concepts, not photographs of manufactured stock. Prices and size options are indicative. Final materials, fit, availability and launch timing are not yet confirmed.</p><h2>Your saved edit</h2><p>The wishlist and preview bag use your browser’s local storage. They are not sent to a customer database or converted into orders. Clear them using the remove controls or your browser’s website-data settings.</p><h2>No payment or email collection</h2><p>This release has no active checkout or email subscription backend. It does not take payment details, place an order or register an email subscription. Web hosting and externally loaded fonts make the network requests required to display the site.</p><h2>Before commercial launch</h2><p>The operating entity, verified contacts, complete privacy information, delivery, returns and purchase terms must be supplied before sales are enabled. This preview information is not a final store policy.</p><a class="button" href="index.html">BACK TO MEMO →</a></section>''')
page('404.html','A Wandering Memory','''<section class="text-page"><p class="eyebrow">404 / A LITTLE DETOUR</p><h1>This memory wandered off.</h1><p>The cat probably knows the way back.</p><a class="button" href="index.html">BACK HOME →</a></section>''')
(D/'catalog.js').write_text('window.MEMO_CATALOG = '+json.dumps(P,ensure_ascii=False)+';\nwindow.MEMO_CATEGORIES = '+json.dumps(CAT,ensure_ascii=False)+';\n')
(D/'CNAME').write_text('memo.saga1001.com\n');(D/'.nojekyll').write_text('')
(D/'robots.txt').write_text('User-agent: *\nAllow: /\nSitemap: https://memo.saga1001.com/sitemap.xml\n')
urls=['','shop.html','travel.html','world.html','size-guide.html','contact.html','policies.html']+['product.html?id='+p['id'] for p in P]
(D/'sitemap.xml').write_text('<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">'+''.join('<url><loc>https://memo.saga1001.com/'+html.escape(u)+'</loc></url>' for u in urls)+'</urlset>\n')
(D/'assets/favicon.svg').write_text('<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64"><rect width="64" height="64" rx="14" fill="#fac8df"/><path d="m14 26 5-16 13 12 14-12 4 17c8 21-8 27-19 26S7 45 14 26Z" fill="none" stroke="#20172a" stroke-width="2.5"/><path d="M22 32h2m16 0h2M29 41h5M6 34l12 2M5 43l13-3m29-4 12-3m-12 8 12 3" stroke="#20172a" stroke-width="2.5" stroke-linecap="round"/></svg>')
(D/'release.json').write_text(json.dumps({'release':V,'domain':'memo.saga1001.com','artwork':'4e10bbe7-7fb1-40b3-9ca0-fbbb60d69e7b.png','source_rgb_sha256':'8d72d82ed792d89d8c139e264c1681eedc82019d337f638564a2120ebd28d8ec','commerce':'preview-only','email_signup':False},indent=2)+'\n')
print('Built',len(list(D.glob('*.html'))),'pages and catalog')
